In [36]:
#Data Manipulation and math
import random
import numpy as np
import pandas as pd

#System performance and Benchmarking
import psutil
import time
import json
import os
from datetime import datetime

Implementation of Linear Search 

- It sequentially searches the input array for the target value and returns whether it was found, its index, and the number of comparisons performed.

In [37]:
class LinearSearch:

    def search(arr, target):

        comparisons = 0

        for index, value in enumerate(arr):

            comparisons += 1

            if value == target:
                return {
                    "found": True,
                    "index": index,
                    "comparisons": comparisons
                }

        return {
            "found": False,
            "index": -1,
            "comparisons": comparisons
        }

Generates randomized input arrays of the specified sizes to be used for benchmarking the linear search algorithm.

In [38]:
def generate_array(size):

    arr = list(range(size))
    random.shuffle(arr)

    return arr

Executes the linear search algorithm across different input sizes and trials while recording:
- runtime
- CPU time
- throughput
- memory usage

and the number of comparisons performed.

In [39]:
def benchmark_linear_search(array_sizes, trials=10):

    process = psutil.Process(os.getpid())
    results = []

    for size in array_sizes:

        print(f"Benchmarking array size {size}...")

        for trial in range(1, trials + 1):

            arr = generate_array(size)

            # Worst case
            target = -1

            cpu_start = time.process_time()
            wall_start = time.perf_counter()

            output = LinearSearch.search(arr, target)

            wall_end = time.perf_counter()
            cpu_end = time.process_time()

            runtime = wall_end - wall_start
            cpu_time = cpu_end - cpu_start

            throughput = size / runtime

            peak_ram = process.memory_info().rss / (1024 * 1024)

            results.append({

                "Array Size": size,
                "Trial": trial,
                "Runtime (s)": runtime,
                "CPU Time (s)": cpu_time,
                "Throughput (elements/s)": throughput,
                "Peak RAM (MB)": peak_ram,
                "Comparisons": output["comparisons"],
                "Found": output["found"]

            })

    return results

Defines the input array sizes and executes the benchmarking function over multiple trials, storing the performance metrics.

In [40]:
array_sizes = [8, 16, 24, 32]

results = benchmark_linear_search(
    array_sizes=array_sizes,
    trials=10
)

Benchmarking array size 8...
Benchmarking array size 16...
Benchmarking array size 24...
Benchmarking array size 32...

Organizes the collected benchmark results into a DataFrame.

In [41]:
df = pd.DataFrame(results)

display(df)

,Array Size,Trial,Runtime (s),CPU Time (s),Throughput (elements/s),Peak RAM (MB),Comparisons,Found
0,8,1,0.000014,0.0,5.882359e+05,112.761719,8,False
1,8,2,0.000007,0.0,1.126761e+06,112.761719,8,False
2,8,3,0.000005,0.0,1.481478e+06,112.761719,8,False
3,8,4,0.000004,0.0,1.860464e+06,112.761719,8,False
4,8,5,0.000004,0.0,1.860464e+06,112.761719,8,False
5,8,6,0.000004,0.0,1.860464e+06,112.761719,8,False
6,8,7,0.000004,0.0,1.904761e+06,112.761719,8,False
7,8,8,0.000004,0.0,2.051282e+06,112.761719,8,False
8,8,9,0.000004,0.0,2.051282e+06,112.761719,8,False
9,8,10,0.000004,0.0,2.162163e+06,112.761719,8,False
10,16,1,0.000006,0.0,2.807025e+06,112.761719,16,False
11,16,2,0.000005,0.0,3.137249e+06,112.761719,16,False
12,16,3,0.000005,0.0,3.137249e+06,112.761719,16,False
13,16,4,0.000005,0.0,3.265301e+06,112.761719,16,False
14,16,5,0.000005,0.0,3.333328e+06,112.761719,16,False
15,16,6,0.000005,0.0,3.333328e+06,112.761719,16,False
16,16,7,0.000005,0.0,3.333348e+06,112.761719,16,False
17,16,8,0.000005,0.0,3.555551e+06,112.761719,16,False
18,16,9,0.000005,0.0,3.404250e+06,112.761719,16,False
19,16,10,0.000005,0.0,3.404250e+06,112.761719,16,False
20,24,1,0.000008,0.0,3.116883e+06,112.761719,24,False
21,24,2,0.000007,0.0,3.636368e+06,112.761719,24,False
22,24,3,0.000006,0.0,3.750006e+06,112.761719,24,False
23,24,4,0.000006,0.0,3.809530e+06,112.761719,24,False
24,24,5,0.000006,0.0,3.692313e+06,112.761719,24,False
25,24,6,0.000006,0.0,3.749988e+06,112.761719,24,False
26,24,7,0.000006,0.0,3.692313e+06,112.761719,24,False
27,24,8,0.000006,0.0,3.809512e+06,112.761719,24,False
28,24,9,0.000006,0.0,3.749988e+06,112.761719,24,False
29,24,10,0.000006,0.0,3.749988e+06,112.761719,24,False
30,32,1,0.000007,0.0,4.444447e+06,112.761719,32,False
31,32,2,0.000007,0.0,4.637685e+06,112.761719,32,False
32,32,3,0.000007,0.0,4.637685e+06,112.761719,32,False
33,32,4,0.000007,0.0,4.507045e+06,112.761719,32,False
34,32,5,0.000007,0.0,4.705867e+06,112.761719,32,False
35,32,6,0.000007,0.0,4.705887e+06,112.761719,32,False
36,32,7,0.000007,0.0,4.705867e+06,112.761719,32,False
37,32,8,0.000007,0.0,4.776125e+06,112.761719,32,False
38,32,9,0.000007,0.0,4.776125e+06,112.761719,32,False
39,32,10,0.000007,0.0,4.705887e+06,112.761719,32,False

Groups the benchmark results by input size and computes the mean and standard deviation of the recorded performance metrics across all trials.

In [42]:
summary_df = (
    df.groupby("Array Size")
      .agg({
          "Runtime (s)": ["mean", "std"],
          "CPU Time (s)": ["mean", "std"],
          "Throughput (elements/s)": ["mean", "std"],
          "Peak RAM (MB)": ["mean", "std"],
          "Comparisons": ["mean", "std"]
      })
)

summary_df

           Runtime (s)               CPU Time (s)       \
                  mean           std         mean  std
Array Size
8             0.000005  3.028398e-06          0.0  0.0
16            0.000005  3.314908e-07          0.0  0.0
24            0.000007  4.143245e-07          0.0  0.0
32            0.000007  1.636376e-07          0.0  0.0

           Throughput (elements/s)                Peak RAM (MB)       \
                              mean            std          mean  std
Array Size
8                     1.694735e+06  493475.370031    112.761719  0.0
16                    3.271088e+06  205269.986437    112.761719  0.0
24                    3.675689e+06  203379.598408    112.761719  0.0
32                    4.660262e+06  108649.442144    112.761719  0.0

           Comparisons
                  mean  std
Array Size
8                  8.0  0.0
16                16.0  0.0
24                24.0  0.0
32                32.0  0.0

Exports the detailed benchmark results to linear_search_results.csv and the aggregated summary statistics to linear_search_summary.csv. 

The detailed results include the array size, trial number, runtime, CPU time, throughput, peak RAM usage, number of comparisons, and search result, while the summary file contains the mean and standard deviation of the recorded performance metrics for each input size.

In [43]:
df.to_csv("linear_search_results.csv", index=False)

summary_df.to_csv("linear_search_summary.csv")